---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: test-kitchen
  ansible_verbose: true
  ansible_verbosity: 2

platforms:
  - name: ubuntu/precise64
  - name: ubuntu/trusty64
  - name: geerlingguy/centos6

suites: 
  - name: default
