# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  def ansible_defaults(ansible)
    if ENV['ANSIBLE_TAGS'] then 
      ansible_tags = ENV['ANSIBLE_TAGS']
      puts "Found ENV variable 'ANSIBLE_TAGS'. Applying tag(s) \"#{ansible_tags}\" to box(es)"
    end
    ansible.playbook = "../playbook.yml"
 #   ansible.inventory_path = "./inventory"
    ansible.verbose = "v"
    ansible.groups = {
      "redhat" => ["centos7"],
      "debian" => ["trusty64"],
      "all" => ["debian","redhat"]    
    }
    ansible.tags = ansible_tags || nil
  end

# Centos 7
  config.vm.define "centos7" do |centos|
    centos.vm.box = "geerlingguy/centos7"
    centos.vm.network "private_network", ip: "192.168.33.30"
    centos.vm.provision :ansible do |ansible|
      ansible_defaults ansible
    end
  end

# Ubuntu 14.04
  config.vm.define "trusty64" do |ubuntu|
    ubuntu.vm.box = "ubuntu/trusty64"
    ubuntu.vm.network "private_network", ip: "192.168.33.31"
    ubuntu.vm.provision :ansible do |ansible|
      ansible_defaults ansible
    end
  end
end
